### ISSUE TITLE
🚀 Feature: Add SEO meta description tag for search results

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/tidelift-me-up-site#67]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/tidelift-me-up-site/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Right now, if you paste any tidelift-me-up-site URL into a place that gives previews (e.g. Bsky/Mastodon/Twitter, Discord/Slack chat, etc.), you get:

> Tidelift Me Up
> Find your npm packages eligible for Tidelift funding. 💸

But for search results such as https://tidelift-me-up-site.vercel.app/?username=joshuakgoldberg&since=, it'd be nice to have a specific message. How about:

> joshuakgoldberg | Tidelift Me Up
> joshuakgoldberg has 1 npm package eligible for Tidelift funding. 💸
